# Generated by Django 2.1.3 on 2018-12-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (4, 'Хорошо'), (3, 'Нормально'), (5, 'Отлично'), (2, 'Плохо')], verbose_name='Оценка'),
        ),
    ]
