# Generated by Django 2.1.3 on 2018-12-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181216_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.IntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально')], verbose_name='Оценка'),
        ),
    ]
