# Generated by Django 2.1.3 on 2018-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181216_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.CharField(choices=[('Ужасно', 'Ужасно'), ('Плохо', 'Плохо'), ('Нормально', 'Нормально'), ('Хорошо', 'Хорошо'), ('Отлично', 'Отлично')], max_length=10, verbose_name='Оценка'),
        ),
    ]
