# Generated by Django 2.1.3 on 2018-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181219_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Оценка'),
        ),
    ]
